# Generated by Django 3.0.6 on 2020-07-09 08:36

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramCats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cat', models.CharField(blank=True, max_length=500)),
                ('cat_description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.ProgramDescription')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('full_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProgramCats')),
            ],
        ),
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=app.models.default_programs_order)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('programs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Program')),
            ],
        ),
    ]
